[REFACT] - lambda service invoke function
Adapcon/adapcon-utils-js pull request #107
Opened 2022-03-03 20:35 UTC by marcosalves-bitg

This PR just refacts the Lambda Invoke function, to use just one.

We divided the invokeLambda function into two, to use one with a custom secret and another (default) passing no secret value.
I refact the two functions into one

2022-03-03 20:38 UTC, marcosalves-bitg commented
Guys! I requested your reviews so we can discuss this again. We, at BombSquad, were not happy with the two functions approach.

2022-03-04 10:49 UTC, marcosalves-bitg commented
PS: We need to improve the version. Is this a Major or a Minor? Or just a Patch?

2022-03-04 11:33 UTC, th3rius commented
> PS: We need to improve the version. Is this a Major or a Minor? Or just a Patch?

Major; this is a breaking change

2022-03-04 11:53 UTC, Viserion77 submitted a review, later dismissed
LGTM

2022-03-04 11:54 UTC, marcosalves-bitg commented
> > PS: We need to improve the version. Is this a Major or a Minor? Or just a Patch?
> 
> Major; this is a breaking change

I agree

2022-03-04 12:04 UTC, mickaelnn requested changes

2022-03-04 12:04 UTC, mickaelnn commented on src/lambda/interfaces.ts
> +export interface SecretValue {
The Secret Value can be an object of any type, the "SecretValue" maybe can be named as "AccessKey" and contain region in this secret also, but as optional

2022-03-04 12:04 UTC, mickaelnn commented on src/lambda/lambdaService.ts
> +      const secretValue: SecretValue = lambdaParameters.serviceSecretArn
here also can be named as accessKey...

2022-03-04 12:12 UTC, mickaelnn requested changes

2022-03-04 12:12 UTC, mickaelnn commented on src/lambda/interfaces.ts
> +  secretAccessKey?: string
this is a mandatory prop

2022-03-04 12:47 UTC, mickaelnn commented
I think this function is an invoke function, this code to get accessKey from secrets manager is another function, and if needed to use with another accessKey, you need to use this by params directly to invoke

obs: this is not the normal flow from an invoke function...

2022-03-04 12:48 UTC, alanneves requested changes

2022-03-04 12:48 UTC, alanneves commented on src/lambda/lambdaService.ts
> +          secretId: lambdaParameters.serviceSecretArn
na minha visão, a lógica do secretmaneger não deve ficar no invoke
o invoke pode receber accessKey, não secretARN, o get do secretARN deveria ser feito antes e só se passado o acesskey

o invoke com  essa lógica do secretManger quebra [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)

2022-03-04 14:12 UTC, mickaelnn approved these changes
LGTM

2022-03-04 14:12 UTC, alanneves submitted a review, later dismissed
removendo request changes solicitado pelo rica

2022-03-04 17:01 UTC, ricardobaehr approved these changes
LGTM

2022-03-04 17:02 UTC, merged