[REFACT]: reorganizing functions
Adapcon/adapcon-utils-js pull request #110
Opened 2022-03-04 20:54 UTC by marcosalves-bitg

This PR is to refact the invoke function and the secretsManager entire folder

2022-03-04 21:00 UTC, Viserion77 commented
quebro

2022-03-04 23:48 UTC, Viserion77 requested changes

2022-03-04 23:48 UTC, Viserion77 commented on src/lambda/lambdaService.ts
> +        ...SecretManager.getAccessKey(lambdaParameters)
```suggestion
        ...await SecretManager.getAccessKey(lambdaParameters)
```

2022-03-05 00:03 UTC, Viserion77 approved these changes
LGTM

2022-03-06 13:13 UTC, marcelbeskow approved these changes
LGTM

2022-03-06 13:14 UTC, merged