feat: added increase, decrease and change date functions
Adapcon/adapcon-utils-js pull request #16
Opened 2021-11-08 00:02 UTC by marcosalves-bitg

### Description

This PR adds three "date manipulation" functions. One to specifically increase a period of time to a date, another to specifically decrease a period of time of a date and a third one that executes the increase/decrease logic. The third function can be called by itself, increasing and decreasing periods on the same call

2021-11-08 00:02 UTC, marcosalves-bitg commented
Guys, let me know if I have to change the package.json version

2021-11-08 10:38 UTC, mickaelnn commented
if You need to use this, You will need to change the package.json to a new version...

About the tests failing, I think have something about the timezone to change

2021-11-09 13:38 UTC, Viserion77 requested changes

2021-11-09 13:38 UTC, Viserion77 commented on src/date/index.ts
> +}
Poderia criar um arquivo separado para isto

2021-11-09 13:38 UTC, Viserion77 commented on src/date/index.ts
> +  date = changeDate(date, duration)
parâmetros imutáveis plz

2021-11-09 17:52 UTC, mickaelnn commented
Precisa dar um npm toda vez que muda versão, se não fizer tem risco de pagar Coca

2021-11-10 11:09 UTC, Viserion77 requested changes

2021-11-10 11:09 UTC, Viserion77 commented on src/date/index.ts
>    return date
```suggestion
  return changeDate(date, decreases)
```

2021-11-10 11:12 UTC, Viserion77 approved these changes
LGTM

2021-11-10 11:30 UTC, mickaelnn submitted a review, later dismissed
LGTM

2021-11-10 12:58 UTC, Viserion77 approved these changes
LGTM

2021-11-10 12:59 UTC, mickaelnn approved these changes
LGTM

2021-11-11 12:32 UTC, alanneves approved these changes
LGTM

2021-11-11 12:49 UTC, merged