[FEAT] create new invoked verifier function
Adapcon/adapcon-utils-js pull request #163
Opened 2022-12-12 14:13 UTC by marcosalves-bitg

Esse PR cria uma pequena função para nos ajudar a validar que tipo de evento esta chegando nos lambdas. Se é um invoked ou se é uma request originária do API Gateway.

2022-12-12 14:14 UTC, marcosalves-bitg commented on __tests__/lambda/lambdaEventChecker.test.ts
> +
```suggestion
```

2022-12-12 14:18 UTC, mickaelnn commented on __tests__/lambda/lambdaEventChecker.test.ts
> +  ]
Consegue simplificar esses dados? acredito que para fakear pode reduzir a quantidade de dados não?

2022-12-12 19:49 UTC, marcosalves-bitg commented on __tests__/lambda/lambdaEventChecker.test.ts
> +  ]
Done!

2022-12-12 20:27 UTC, gabrielforster approved these changes

2022-12-13 10:37 UTC, caroltrindade requested changes

2022-12-13 10:37 UTC, caroltrindade commented on src/lambda/lambdaEventChecker.ts
> +    if (Object.keys(event.requestContext as object).length) {
N'ao sera mais prático fazer uma só validação? Sem precisar encadear esses IFs?
Exemplo: if (event?.requestContext && Object.keys(event?.requestContext).length)

2022-12-13 10:37 UTC, caroltrindade commented on src/lambda/lambdaEventChecker.ts
> +        invoke: false
Não seria mais correto só retornar true ou false?

2022-12-13 10:37 UTC, caroltrindade commented on src/lambda/event.ts
> +export const lambdaRequestEventExample = {
Seu mock de dados está no /src? Acredito que deveria estar dentro da pasta /_tests_/lambda ou  /_tests_/lambda/mocks. ou ainda deixar esse mock diretamente dentro do arquivo de teste do lambdaEventChecker

2022-12-13 10:55 UTC, marcosalves-bitg commented on src/lambda/event.ts
> +export const lambdaRequestEventExample = {
Vou mudar a localização. Concordo!

2022-12-13 10:55 UTC, marcosalves-bitg commented on src/lambda/lambdaEventChecker.ts
> +        invoke: false
Boa!

2022-12-13 10:59 UTC, marcosalves-bitg commented on src/lambda/lambdaEventChecker.ts
> +    if (Object.keys(event.requestContext as object).length) {
will do

2022-12-13 11:11 UTC, caroltrindade approved these changes
LGTM

2022-12-13 11:36 UTC, mickaelnn requested changes

2022-12-13 11:36 UTC, mickaelnn commented on src/lambda/lambdaEventChecker.ts
> +  return true
```suggestion
  return ('requestContext' in event) && (Object.keys(event.requestContext as object).length)
```

2022-12-13 11:54 UTC, caroltrindade approved these changes
LGTM

2022-12-13 11:56 UTC, mickaelnn approved these changes
LGTM

2022-12-13 11:56 UTC, caroltrindade requested changes

2022-12-13 11:56 UTC, caroltrindade commented on src/lambda/lambdaEventChecker.ts
> +  return !(('requestContext' in event) && !!(Object.keys(event.requestContext).length))
Ta certo ter a negação na frente?

2022-12-13 12:00 UTC, caroltrindade commented on src/lambda/lambdaEventChecker.ts
> +  return !(('requestContext' in event) && !!(Object.keys(event.requestContext).length))
esquece, essa condição retornava true

2022-12-13 12:01 UTC, caroltrindade approved these changes
LGTM

2022-12-13 12:06 UTC, marcosalves-bitg commented on src/lambda/lambdaEventChecker.ts
> +  return !(('requestContext' in event) && !!(Object.keys(event.requestContext).length))
Sim! É que se tem, é por que é uma request. Ai como estamos validando se é invoked, tem que "não ter" a parada la

2022-12-13 12:06 UTC, merged