Feat/improve constants
Adapcon/adapcon-utils-js pull request #50
Opened 2021-12-16 17:49 UTC by marcosalves-bitg

This PR adds some improvements to http messages and status constants.
They're now enums. And we now have a function that returns a default response object with a correct name is sent

2021-12-16 17:52 UTC, Viserion77 submitted a review, later dismissed
LGTM

2021-12-16 17:56 UTC, Viserion77 approved these changes
IATB

2021-12-16 18:16 UTC, ixpd submitted a review, later dismissed
LGTM

2021-12-17 11:05 UTC, GabrielPedrotti submitted a review, later dismissed
LGTM

2021-12-31 06:20 UTC, alanneves commented on src/http/enums.ts
> +export enum HttpNames {
That makes sense?

2021-12-31 06:20 UTC, alanneves requested changes
That makes sense?

2021-12-31 06:21 UTC, alanneves requested changes

2021-12-31 06:21 UTC, alanneves commented on src/http/enums.ts
> +export enum HttpNames {
That makes sense?

2022-01-07 18:01 UTC, Viserion77 approved these changes
ELGETEEME

2022-01-07 18:47 UTC, alanneves approved these changes
LGTM

2022-01-07 18:50 UTC, merged