Feature/secret manager
Adapcon/adapcon-utils-js pull request #73
Opened 2022-01-29 14:02 UTC by Viserion77

this pr adds a new function to get value from the SM service of AWS.
the test was be ignored because use a was SDK, and I don't know test it.

2022-01-29 14:08 UTC, marcosalves-bitg approved these changes
LGTM

2022-01-29 15:37 UTC, Viserion77 commented
This pr was been tested on my computer, and this works!

2022-01-29 16:56 UTC, marcosalves-bitg approved these changes
LGTM

2022-01-31 11:07 UTC, th3rius commented
But why not use the SDK directly? Is there a functionality you're trying to abstract?

2022-01-31 11:13 UTC, mickaelnn requested changes

2022-01-31 11:13 UTC, mickaelnn commented on src/lambda/lambdaService.ts
>  import AWS from 'aws-sdk'
Não gostei do jeito que está sendo passado isso para o LambdaService, eu não acho que deveriamos ter um if dentro deste invoke, acredito que exista outros meios de tu passar as keys para esse cara sem precisar desse if...

Caso não tenha outro jeito acharia melhor ainda criar um novo invoke com credenciais para não deixar esse IF

2022-01-31 11:42 UTC, alanneves commented
> But why not use the SDK directly? Is there a functionality you're trying to abstract?

He's trying to access a lambda function from another AWS account. He can access if registers Adapcon credentials in the secret manager of AMC and pass it in the request. I don't think this is a good approach

2022-01-31 16:40 UTC, ricardobaehr submitted a review, later dismissed
LGTM

Oi gente, dentre as alternativas possíveis, guardar uma key dentro do secret manager na conta da AMC é a mais viável.

Porém deve ser uma key com somente permissão de lambda invoke (podemos estudar se para todos os lambdas ou se vamos especificar cada um).

2022-01-31 17:28 UTC, th3rius commented
> He's trying to access a lambda function from another AWS account. He can access if registers Adapcon credentials is in the secret manager of AMC and pass it in the request. I don't think this is a good approach

Sure enough — I just didn't get why we need `SecretManager` when it pretty much does the same thing as the AWS SDK. This

```ts
const client = new AWS.SecretsManager()
// The SDK can also return a promise calling `promise`
const secret = await client.getSecretValue({SecretId: id}).promise()
if (!secret) throw new Error("Secret not found")
const {accessKeyId, secretAccessKey} = JSON.parse(secret.SecretString)
```

is much cleaner than creating another level of abstraction we're perfectly fine without. @alanneves @ricardobaehr what do you think?

2022-02-01 20:27 UTC, mickaelnn approved these changes
LGTM

2022-02-01 20:38 UTC, th3rius approved these changes

2022-02-01 20:40 UTC, merged